### PR TITLE
AppReview/Mobile | improved questions style and animations

### PR DESCRIPTION
**Pull request by chrisdugne**
**Detailed purpose of the PR**

- Now it's possible to scroll a large amount of choices
- Improved style + animations

### CODE REVIEW

**Comment by chrisdugne** [comment]
[[OR] Mobile - Bug style QCM slide](https://trello.com/c/5KmpnMsr/2882-or-mobile-bug-style-qcm-slide)

**Comment by chrisdugne** [comment]
[[OR] Mobile - Bug style qcmGraphicSlide](https://trello.com/c/7Jby0V5L/2883-or-mobile-bug-style-qcmgraphicslide)

**Comment by chrisdugne** [comment]
[[OR] Mobile - Bug question masquée](https://trello.com/c/KZUhDgky/2900-or-mobile-bug-question-masqu%C3%A9e)

**Comment by chrisdugne** [comment]
[[OR] Bug affichage des slides sur mobile](https://trello.com/c/ydpuxCwb/2875-or-bug-affichage-des-slides-sur-mobile)

**Review by jomaora — APPROVED** [review]

**Comment by chrisdugne** [comment]
[[OR] Update du style des questions app-mobile](https://trello.com/c/b8nBb46M/2729-or-update-du-style-des-questions-app-mobile)

**Pull request merged**
